export type LogoCliente = {
  nombre: string;
  src: string;
  slug?: string;
};

export const logosClientes: LogoCliente[] = [
  { nombre: "Mercado Libre", src: "/images/logos/Logo-ML.jpg" },
  { nombre: "Techint", src: "/images/logos/TM-Logo.jpg" },
  { nombre: "Tenaris", src: "/images/logos/tenaris.png" },
  { nombre: "Ternium", src: "/images/logos/ternium.jpg" },
  { nombre: "BASF", src: "/images/logos/BASF-Logo.png" },
  { nombre: "Aeropuertos Argentina 2000", src: "/images/logos/logo-aeropuertos-2000.jpg" },
  { nombre: "Dell EMC", src: "/images/logos/logo-EMC.jpg" },
  { nombre: "Dell Technologies", src: "/images/logos/dell-technologies-logo.png" },
  { nombre: "Lenovo", src: "/images/logos/lenovo-logo-1000x333.png" },
  { nombre: "DirecTV", src: "/images/logos/directv_logo.png" },
  { nombre: "Multicanal", src: "/images/logos/preview-Multicanal.png" },
  { nombre: "Edesur", src: "/images/logos/Edesur-Logo.jpg" },
  { nombre: "Prosegur", src: "/images/logos/Logo-Prosegur.png" },
  { nombre: "Gerdau", src: "/images/logos/logo-gerdau-.jpg" },
  { nombre: "Arcor", src: "/images/logos/arcor-logo.jpg" },
  { nombre: "American Express", src: "/images/logos/Logo-American-Express.png" },
  { nombre: "TGP", src: "/images/logos/logo-tgp.jpg" },
  { nombre: "TGN", src: "/images/logos/tgn.jpg" },
  { nombre: "COGA", src: "/images/logos/logo-coga.jpg" },
  { nombre: "Naranja", src: "/images/logos/logo-naranja.jpg" },
  { nombre: "Banco Galicia", src: "/images/logos/banco-galicia.png" },
  { nombre: "Clarín", src: "/images/logos/clarin.png" },
  { nombre: "Radio Mitre", src: "/images/logos/mitre_am.jpg" },
  { nombre: "La Nación", src: "/images/logos/La_Nacion_Logo.png" },
  { nombre: "Adecco", src: "/images/logos/adecco.png" },
  { nombre: "IAE Business School", src: "/images/logos/IAE_Business_School_logo.jpg" },
  { nombre: "IDEA", src: "/images/logos/logo_idea.jpg" },
  { nombre: "Tramando", src: "/images/logos/Tramando-logo.jpg" },
  { nombre: "Edrans", src: "/images/logos/logo-edrans.png" },
  { nombre: "Timbó", src: "/images/logos/Timbo-logo.jpg" },
  { nombre: "47 Street", src: "/images/logos/47-street.jpg" },
  { nombre: "Gentos", src: "/images/logos/Logo-Gentos.jpg" },
  { nombre: "Footy", src: "/images/logos/logo-footy.jpg" },
  { nombre: "Accendo", src: "/images/logos/logo-accendo.jpg" },
  { nombre: "Agroindustrias Baires", src: "/images/logos/logo-agroindustrias-baires.png" },
  { nombre: "La Gloriosa", src: "/images/logos/logo-La-Gloriosa.png" },
  { nombre: "The Lucky", src: "/images/logos/Logo-The-Lucky.png" },
  { nombre: "CHS", src: "/images/logos/chslogo-v3.png" },
  { nombre: "Tandem", src: "/images/logos/Tandem.png" },
  { nombre: "AVNC", src: "/images/logos/logo_AVNC.png" },
  { nombre: "Cinalli", src: "/images/logos/Logo-Cinalli.jpg" },
  { nombre: "Repicky", src: "/images/logos/Logo-Repicky-.png" },
  { nombre: "Ferrum", src: "/images/logos/ferrum.jpg" },
  { nombre: "Club Tigre", src: "/images/logos/escudo-tigre.jpg" },
  { nombre: "Rex Pintureria", src: "/images/logos/rex_pintureria_logo.jpg" },
  { nombre: "Akian", src: "/images/logos/akian_grafica.png" },
  { nombre: "Microglobal", src: "/images/logos/microglobal.jpg" },
  { nombre: "Raffo", src: "/images/logos/raffo.jpg" },
  { nombre: "Ventalum", src: "/images/logos/ventalum.jpg" },
  { nombre: "PSA", src: "/images/logos/PSA_enero12.jpg" },
  { nombre: "Argenprint", src: "/images/logos/Argenprint.jpg" },
  { nombre: "Mseg", src: "/images/logos/Mseg.jpg" },
  { nombre: "Blue HG", src: "/images/logos/blue_hg.jpg" },
  { nombre: "Giovanna di Firenze", src: "/images/logos/giovannadifirenze2.png" },
];
